### PR TITLE
Increase menu flashing duration and add mouse support

### PR DESCRIPTION
**Pull request by Dimi20cen**
- Replace division operator with floor division operator for equation to equates to 1 for a bigger range and make the text more readable
Add mouse support, Fixes#4
- For starting game
- For entering help
- For exiting help
	- Add exit button in help page

@chimosky @sourabhaa

### CODE REVIEW

**Comment by Dimi20cen** [comment]
@chimosky, Could you check again if the issue with the key press events still persists?

**Comment by chimosky** [comment]
Update sugargame instead of d72725c as changes are better at sugargame as they're universal and changing it here makes it particular to this activity, and the change has also been made in sugargame.

**Comment by Dimi20cen** [comment]
I didn't change the sugargame, I just replaced it with it's newest version. Maybe my commit message didn't reflect what I actually did.

**Comment by Dimi20cen** [comment]
With the update of sugargame, is #11 unnecessary?

**Comment by chimosky** [comment]
> With the update of sugargame, is #11 unnecessary?

There's the possibility but I'll have to test to confirm.

**Comment by Dimi20cen** [comment]
Tested, works as expected, thanks!

**Comment by Dimi20cen** [comment]
Hey, is this okay to merge?

**Comment by chimosky** [comment]
e04e556 on master updates sugargame so you'll need to drop 0934e3d.

d72725c should also be dropped.

**Comment by chimosky** [comment]
Merged  by hand, I dropped the two commits myself. Thanks!

**Pull request closed without merging**
