### PR TITLE
Fix key press events not handled

### PR DESCRIPTION
**Pull request by chimosky**
On activity start, the activity doesn't hanlde any key press and this fixes that.

Other issues like canvas not resizing according to screen size still exist.

@jriyyya @Dimi20Cen kindly test.

Dimitris, does #10 work without issues for you as the activity doesn't work for me without this fix.

### CODE REVIEW

**Comment by Dimi20cen** [comment]
For me the activity handles key presses as expected when I run it on my vm, which runs on the sugar's live-build. However as you said, when I run the activity with "sugar-activity3 .", it doesn't handle any key press events.
Similarly, same goes for #10.

**Comment by Dimi20cen** [comment]
Also Ibiam, I just tried your fix for when I run the activity with `sugar-activity3 .` and I still have the same issue. To be exact, I get something like the following 
```Traceback (most recent call last):
  File "/home/dim/Documents/GitHub/cellgame/sugargame/event.py", line 128, in _keydown_cb
    return self._keyevent(widget, event, pygame.KEYDOWN)
  File "/home/dim/Documents/GitHub/cellgame/sugargame/event.py", line 169, in _keyevent
    mod = self._keymods()
  File "/home/dim/Documents/GitHub/cellgame/sugargame/event.py", line 145, in _keymods
    mod |= self.__keystate[key_val] and mod_val
IndexError: list index out of range
```

Do you have the same issue?

**Comment by Dimi20cen** [comment]
Hey again, Ibiam, configuring the sugargame/event.py file by adding try-except around `mod |= self.__keystate[key_val] and mod_val` solves the issue for me, since it ignores the handling from the event.py.

**Comment by Dimi20cen** [comment]
Okay, nevermind I just saw you have recently updated sugargame. So replacing the old event.py with the new one solves the issue for me. Thank you for the event.py change, saved me lots of debugging.

**Comment by Dimi20cen** [comment]
Update, the following lines because issue to my vm installation.
- pygame.K_PERCENT
- pygame.K_SCROLLLOCK
- pygame.K_CURRENCYUNIT
- pygame.K_CURRENCYSUBUNIT
- pygame.K_AC_BACK

Specifically I would get something like the following 
```
Traceback (most recent call last):
  File "/usr/bin/sugar-activity3", line 5, in <module>
    activityinstance.main()
  File "/usr/lib/python3.7/dist-packages/sugar3/activity/activityinstance.py", line 179, in main
    module = __import__(module_name)
  File "/home/dim/Activities/cellgame/activity.py", line 24, in <module>
    import sugargame.canvas
  File "/home/dim/Activities/cellgame/sugargame/canvas.py", line 28, in <module>
    import sugargame.event as event
  File "/home/dim/Activities/cellgame/sugargame/event.py", line 35, in <module>
    class Translator(object):
  File "/home/dim/Activities/cellgame/sugargame/event.py", line 201, in Translator
    pygame.K_AC_BACK
AttributeError: module 'pygame' has no attribute 'K_AC_BACK'
```

To clarify, my vm runs pygame1.9.4.post1 and when I test activities with `sugar-activity3 .` it runs pygame 2.4.0

**Comment by chimosky** [comment]
> Do you have the same issue?

No I don't and I hardly run activities with `sugar-activity3`.

**Comment by Dimi20cen** [comment]
Got it, what is the issue you face?

**Comment by chimosky** [comment]
> Update, the following lines because issue to my vm installation.

>    pygame.K_PERCENT
>    pygame.K_SCROLLLOCK
>    pygame.K_CURRENCYUNIT
>    pygame.K_CURRENCYSUBUNIT
>    pygame.K_AC_BACK


What version of pygame are you running?  All the keys [exist](https://github.com/pygame/pygame/blob/main/src_c/key.c)

> Got it, what is the issue you face?

Testing HEAD at master and no key press events are handled and at the start of the activity you're told to press any key so activity stops at the instruction screen and shows nothing else.

**Comment by Dimi20cen** [comment]
>What version of pygame are you running? 

My vm runs pygame1.9.4.post1 and when I test activities with `sugar-activity3 .`, it runs pygame 2.4.0

>Testing HEAD at master and no key press events are handled and at the start of the activity you're told to press any key so activity stops at the instruction screen and shows nothing else.

Got it, don't you get any Tracebacks or errors?

**Comment by chimosky** [comment]
> My vm runs pygame1.9.4.post1 and when I test activities with sugar-activity3 ., it runs pygame 2.4.0

That's strange, it should run 2.4.0 regardless, I'm running 2.5.0.

> Got it, don't you get any Tracebacks or errors?

Same thing you shared above;

```python3
  File "/home/dim/Documents/GitHub/cellgame/sugargame/event.py", line 128, in _keydown_cb
    return self._keyevent(widget, event, pygame.KEYDOWN)
  File "/home/dim/Documents/GitHub/cellgame/sugargame/event.py", line 169, in _keyevent
    mod = self._keymods()
  File "/home/dim/Documents/GitHub/cellgame/sugargame/event.py", line 145, in _keymods
    mod |= self.__keystate[key_val] and mod_val
 IndexError: list index out of range
```

**Comment by chimosky** [comment]
Closing as key press issue was fixed in sugargame and updating here fixes this.

**Pull request closed without merging**
