### PR TITLE
Add music and mouse click sound effect

### PR DESCRIPTION
**Pull request by SohamKukreti**
Hi, I felt that cellgame would be more immersive and would be an overall better experience for the users if it had music and some sound effects, so I have created some music for the game and I have added a sound effect when the user clicks the mouse.

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.

* [x] please comply with imperative tense recommendation in how to make commits,
* [x] the files are wav format, and the theme about 7mb for 38 seconds, can they be mp3 or ogg instead?
* [x] the theme file name contains cell, which is unnecessary,
* [x] the theme repeats after only 38 seconds, why did you choose this time?
* [x] the click sound is inaudible; opening in audacity shows it to be very low energy,
* [x] please confirm the sounds are your own work so as to comply with the license of the app,
* [x] please remove the unnecessary comment "#music",
* [x] why is the sound effect missing from the other two event loops?

**Comment by SohamKukreti** [comment]
Thanks for the review quozl.
1) I'll make sure to follow the imperative tense recommendation
2) Yes I can insert the mp3/ogg files instead of the wav files.
3) I'll remove cells from the theme song.
4) When I was making the track, it looped well around 38 seconds, so I decided to set that as the length of the song, however I can change it, that won't be an issue.
5) The song is my own work and the click sound effect is released under Creative Commons 0 "([CC0](https://creativecommons.org/publicdomain/zero/1.0/))"
6) I'll remove the comment from the code.
7) I was thinking of having the click sound effect only while the main game was running, however I can add it to the other event loops too. Currently, the sound effect doesn't play on the help screen.

**Comment by quozl** [comment]
Good, thanks.  Please also rewrite your commit message to include these decisions (4, 5, 7), from the perspective of what is proposed to be changed from _master_ branch.  Thanks.

**Comment by SohamKukreti** [comment]
Hi, I have made the required changes.

**Comment by quozl** [comment]
Thanks.  I expect to review by 9th February.

**Comment by quozl** [comment]
For next time;

* please don't use your master branch, as it stops any of us pushing changes.

So I merged by hand.

**Pull request merged**
